#!/bin/bash
#
# Helper script for downloadGATKReportsFromS3.sh that downloads and parses
# a single chunk's worth of GATK reports from the specified S3 bucket/account.
#
# Usage: downloadGATKReportsChunk.sh chunk_name s3_bucket s3_config_file
#
# chunk_name      Name of a file in ${download_root} containing a list of files
#                 to download from the bucket, as generated by s3cmd ls.
#
# s3_bucket       Name of the S3 bucket to download from
#
# s3_config_file  Config file to use for s3cmd with S3 account credentials
#

s3_root_dir="/humgen/gsa-hpprojects/GATK/reports/s3"
s3_config_dir="${s3_root_dir}/config"
archive_dir="${s3_root_dir}/archive"
download_root="/local/gsa-engineering/GATKLogs"
script_dir="/local/gsa-engineering/cron_clones/unstable/private/GATKLogs"

log_event() {
    echo `date` " -- $1"
}

if [ $# -ne 3 ]
then
    echo "Usage: $0 chunk_name s3_bucket s3_config_file"
    exit 1
fi

chunk="$1"
s3_bucket="$2"
s3_config_file="$3"

download_dir="${download_root}/${chunk}_files"
raw_archive="${archive_dir}/${chunk}.raw_files.gz"
xml_archive="${archive_dir}/${chunk}.xml.gz"

cd "${download_root}"

log_event "Downloading files for chunk ${chunk}"
python "${script_dir}/manageGATKS3Logs.py" -b "${s3_bucket}" -c "${s3_config_file}" -p 10 -g 100 -d "${download_dir}" move "${chunk}" "progress_${chunk}.log"
log_event "Done downloading files for chunk ${chunk}"

log_event "Archiving raw files for chunk ${chunk}"
tar -czf "${raw_archive}" -C "${download_root}" "${chunk}_files"
log_event "Done archiving raw files for chunk ${chunk}"

log_event "Parsing report files for chunk ${chunk}"
python "${script_dir}/analyzeRunReports.py" archive "${download_dir}" -o "${xml_archive}" -D
log_event "Done parsing report files for chunk ${chunk}"

log_event "Loading reports to database for chunk ${chunk}"
python "${script_dir}/analyzeRunReports.py" loadToDB "${xml_archive}"
log_event "Done loading reports to database for chunk ${chunk}"

mv "${chunk}" "${archive_dir}/${chunk}.ls"
rm -f "progress_${chunk}.log"
rmdir "${download_dir}"

touch "${download_root}/${chunk}.done"

exit 0
