#!/bin/zsh

for file in `git diff-index --name-only HEAD`
do
    echo -n "checking license on $file... ";
	if [[ "${file##*.}" == "java"  ||  "${file##*.}" == "scala" ]]
	then
        private/shell/updateLicenseForFile.sh $file;
        result=$?;
        if [[ $result != 0 ]]
        then
            exit $result;
        else
            echo "OK";
        fi
	else
	    echo "doesn't need a license (not java or scala)";
	fi
done